name: PetPlugin
api-version: 1.16
version: 0.1
author: nimble0
description: Your favorite Pet Plugin

depend: [ProtocolLib]

main: de.nimble.PetPlugin

commands:
  pet:
    usage: /pet
    description: Pet Command